import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import clsx from "clsx";
import { Montserrat } from "next/font/google";
import ReduxProvider from "@/src/lib/provider";
import { SessionProvider } from "next-auth/react";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative">
      <body className={clsx(montserrat.className)}>
        {" "}
        <SessionProvider>
          <ReduxProvider>
            {children} 
            </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
